In [1]:
import pandas as pd

In [2]:
rdd = pd.read_csv('rdd22.csv')
rdd

,Country,Year,Energy efficiency,Fossil fuels,Hydrogen and fuel cells,Nuclear,Other power and storage technologies,Renewables
0,Australia,2000,0.000,0.000,0.000,0.000,0.000,0.000
1,Australia,2001,17.152,118.584,0.000,5.329,10.331,19.396
2,Australia,2002,0.000,0.000,0.000,0.000,0.000,0.000
3,Australia,2003,15.887,97.503,0.000,1.580,7.360,18.977
4,Australia,2004,55.633,61.956,0.343,35.143,11.036,44.505
...,...,...,...,...,...,...,...,...
831,United States,2017,1974.924,576.251,119.254,1053.926,240.804,794.754
832,United States,2018,2464.632,678.637,132.597,1244.294,147.265,870.584
833,United States,2019,2549.316,666.958,135.924,1488.371,394.698,1051.688
834,United States,2020,2783.658,670.056,181.172,1598.394,474.293,1080.309
835,United States,2021,2751.490,691.238,128.406,1859.747,448.005,1111.676

In [3]:
co2 = pd.read_excel('co2_2.xlsx')
co2

            Country  Year  Emission
0         Australia  2000    274.33
1           Austria  2000     54.99
2           Belgium  2000       NaN
3            Canada  2000    434.69
4    Czech Republic  2000    111.98
..              ...   ...       ...
589  United Kingdom  2021       NaN
590   United States  2021       NaN
591             IEA  2021   8775.81
592          Brazil  2021       NaN
593        Slovenia  2021       NaN

[594 rows x 3 columns]

In [4]:
df = pd.merge_ordered(co2, rdd)
df

,Country,Year,Emission,Energy efficiency,Fossil fuels,Hydrogen and fuel cells,Nuclear,Other power and storage technologies,Renewables
0,Australia,2000,274.33,0.000,0.000,0.000,0.000,0.000,0.000
1,Australia,2001,281.47,17.152,118.584,0.000,5.329,10.331,19.396
2,Australia,2002,285.92,0.000,0.000,0.000,0.000,0.000,0.000
3,Australia,2003,289.42,15.887,97.503,0.000,1.580,7.360,18.977
4,Australia,2004,300.42,55.633,61.956,0.343,35.143,11.036,44.505
...,...,...,...,...,...,...,...,...,...
853,United States,2017,4196.40,1974.924,576.251,119.254,1053.926,240.804,794.754
854,United States,2018,4266.79,2464.632,678.637,132.597,1244.294,147.265,870.584
855,United States,2019,4222.79,2549.316,666.958,135.924,1488.371,394.698,1051.688
856,United States,2020,3615.86,2783.658,670.056,181.172,1598.394,474.293,1080.309
857,United States,2021,NaN,2751.490,691.238,128.406,1859.747,448.005,1111.676

In [5]:
df.dropna(inplace=True, ignore_index = True)
df

,Country,Year,Emission,Energy efficiency,Fossil fuels,Hydrogen and fuel cells,Nuclear,Other power and storage technologies,Renewables
0,Australia,2000,274.33,0.000,0.000,0.000,0.000,0.000,0.000
1,Australia,2001,281.47,17.152,118.584,0.000,5.329,10.331,19.396
2,Australia,2002,285.92,0.000,0.000,0.000,0.000,0.000,0.000
3,Australia,2003,289.42,15.887,97.503,0.000,1.580,7.360,18.977
4,Australia,2004,300.42,55.633,61.956,0.343,35.143,11.036,44.505
...,...,...,...,...,...,...,...,...,...
513,United States,2016,4241.08,1868.364,597.518,121.460,1029.452,205.570,866.341
514,United States,2017,4196.40,1974.924,576.251,119.254,1053.926,240.804,794.754
515,United States,2018,4266.79,2464.632,678.637,132.597,1244.294,147.265,870.584
516,United States,2019,4222.79,2549.316,666.958,135.924,1488.371,394.698,1051.688
517,United States,2020,3615.86,2783.658,670.056,181.172,1598.394,474.293,1080.309

In [6]:
df.to_excel('data.xlsx', index=False)

In [14]:
year = pd.Categorical(df.Year)

In [15]:
df = df.set_index(["Country", "Year"])

In [16]:
exog_vars = df.columns.tolist()
exog_vars.pop(0)
exog_vars

['Energy efficiency',
 'Fossil fuels',
 'Hydrogen and fuel cells',
 'Nuclear',
 'Other power and storage technologies',
 'Renewables']

In [18]:
import statsmodels.api as sm

In [19]:
exog = sm.add_constant(df[exog_vars])

In [20]:
from linearmodels.panel import PooledOLS

In [21]:
mod = PooledOLS(df.Emission, exog)

In [22]:
pooled_res = mod.fit()

In [23]:
pooled_res

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:               Emission   R-squared:                        0.8569
Estimator:                  PooledOLS   R-squared (Between):              0.9216
No. Observations:                 518   R-squared (Within):              -9.2342
Date:                Fri, Nov 24 2023   R-squared (Overall):              0.8569
Time:                        12:55:57   Log-likelihood                   -4210.8
Cov. Estimator:            Unadjusted
                                        F-statistic:                      510.13
Entities:                          26   P-value                           0.0000
Avg Obs:                       19.923   Distribution:                   F(6,511)
Min Obs:                       11.000
Max Obs:                       22.000   F-statistic (robust):             510.13
                                        P-value                           0.0000
Time periods:                      22   Distribution:                   F(6,511)
Avg Obs:                       23.545
Min Obs:                       6.0000
Max Obs:                       26.000

                                          Parameter Estimates
========================================================================================================
                                      Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------
const                                    68.836     39.124     1.7594     0.0791     -8.0280      145.70
Energy efficiency                        0.9046     0.1765     5.1258     0.0000      0.5579      1.2513
Fossil fuels                             0.7520     0.1598     4.7052     0.0000      0.4380      1.0660
Hydrogen and fuel cells                 -0.4813     0.4088    -1.1773     0.2396     -1.2845      0.3219
Nuclear                                  0.8982     0.0622     14.437     0.0000      0.7760      1.0205
Other power and storage technologies    -0.4331     0.5129    -0.8445     0.3988     -1.4407      0.5745
Renewables                              -0.0724     0.1846    -0.3924     0.6950     -0.4351      0.2903
========================================================================================================
PanelResults, id: 0x1e44231ae90

In [24]:
from linearmodels.panel import RandomEffects

In [25]:
mod = RandomEffects(df.Emission, exog)

In [26]:
re_res = mod.fit()
re_res

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:               Emission   R-squared:                        0.4015
Estimator:              RandomEffects   R-squared (Between):              0.0614
No. Observations:                 518   R-squared (Within):               0.7168
Date:                Fri, Nov 24 2023   R-squared (Overall):              0.0660
Time:                        12:57:25   Log-likelihood                   -3444.5
Cov. Estimator:            Unadjusted
                                        F-statistic:                      57.122
Entities:                          26   P-value                           0.0000
Avg Obs:                       19.923   Distribution:                   F(6,511)
Min Obs:                       11.000
Max Obs:                       22.000   F-statistic (robust):             57.698
                                        P-value                           0.0000
Time periods:                      22   Distribution:                   F(6,511)
Avg Obs:                       23.545
Min Obs:                       6.0000
Max Obs:                       26.000

                                          Parameter Estimates
========================================================================================================
                                      Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------
const                                    746.43     103.95     7.1810     0.0000      542.22      950.64
Energy efficiency                       -0.4186     0.0512    -8.1798     0.0000     -0.5191     -0.3180
Fossil fuels                             0.1191     0.0422     2.8191     0.0050      0.0361      0.2021
Hydrogen and fuel cells                 -0.0066     0.0945    -0.0697     0.9445     -0.1921      0.1790
Nuclear                                  0.2828     0.0372     7.5984     0.0000      0.2097      0.3560
Other power and storage technologies     0.2210     0.1532     1.4422     0.1499     -0.0801      0.5221
Renewables                              -0.0108     0.0452    -0.2380     0.8120     -0.0996      0.0781
========================================================================================================
RandomEffectsResults, id: 0x1e44235fbe0

In [27]:
from linearmodels.panel import BetweenOLS

In [28]:
mod = BetweenOLS(df.Emission, exog)
be_res = mod.fit(reweight=True)
be_res

                         BetweenOLS Estimation Summary
================================================================================
Dep. Variable:               Emission   R-squared:                        0.9952
Estimator:                 BetweenOLS   R-squared (Between):              0.9949
No. Observations:                  26   R-squared (Within):              -64.853
Date:                Fri, Nov 24 2023   R-squared (Overall):              0.5667
Time:                        12:59:21   Log-likelihood                   -167.05
Cov. Estimator:            Unadjusted
                                        F-statistic:                      667.40
Entities:                          26   P-value                           0.0000
Avg Obs:                       19.923   Distribution:                    F(6,19)
Min Obs:                       11.000
Max Obs:                       22.000   F-statistic (robust):             661.26
                                        P-value                           0.0000
Time periods:                      22   Distribution:                    F(6,19)
Avg Obs:                       23.545
Min Obs:                       6.0000
Max Obs:                       26.000

                                          Parameter Estimates
========================================================================================================
                                      Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------
const                                    21.110     37.650     0.5607     0.5816     -57.693      99.913
Energy efficiency                        2.5922     0.5750     4.5086     0.0002      1.3888      3.7956
Fossil fuels                             0.7792     0.4684     1.6636     0.1126     -0.2011      1.7595
Hydrogen and fuel cells                 -3.6395     4.0329    -0.9024     0.3781     -12.080      4.8015
Nuclear                                 -0.3482     0.2163    -1.6099     0.1239     -0.8009      0.1045
Other power and storage technologies    -3.2606     1.3667    -2.3858     0.0276     -6.1210     -0.4001
Renewables                               2.1403     1.0320     2.0739     0.0519     -0.0197      4.3004
========================================================================================================
PanelResults, id: 0x1e442371000

In [29]:
from linearmodels.panel import compare

In [30]:
print(compare({"BE": be_res, "RE": re_res, "Pooled": pooled_res}, stars=True))

                                Model Comparison
================================================================================
                                                 BE              RE       Pooled
--------------------------------------------------------------------------------
Dep. Variable                              Emission        Emission     Emission
Estimator                                BetweenOLS   RandomEffects    PooledOLS
No. Observations                                 26             518          518
Cov. Est.                                Unadjusted      Unadjusted   Unadjusted
R-squared                                    0.9952          0.4015       0.8569
R-Squared (Within)                          -64.853          0.7168      -9.2342
R-Squared (Between)                          0.9949          0.0614       0.9216
R-Squared (Overall)                          0.5667          0.0660       0.8569
F-statistic                                  667.40          57.122       510.13
P-value (F-stat)                             0.0000          0.0000       0.0000
====================================== ============ =============== ============
const                                        21.110       746.43***      68.836*
                                           (0.5607)        (7.1810)     (1.7594)
Energy efficiency                         2.5922***      -0.4186***    0.9046***
                                           (4.5086)       (-8.1798)     (5.1258)
Fossil fuels                                 0.7792       0.1191***    0.7520***
                                           (1.6636)        (2.8191)     (4.7052)
Hydrogen and fuel cells                     -3.6395         -0.0066      -0.4813
                                          (-0.9024)       (-0.0697)    (-1.1773)
Nuclear                                     -0.3482       0.2828***    0.8982***
                                          (-1.6099)        (7.5984)     (14.437)
Other power and storage technologies      -3.2606**          0.2210      -0.4331
                                          (-2.3858)        (1.4422)    (-0.8445)
Renewables                                  2.1403*         -0.0108      -0.0724
                                           (2.0739)       (-0.2380)    (-0.3924)
--------------------------------------------------------------------------------

T-stats reported in parentheses

In [31]:
from statsmodels.stats.diagnostic import het_breuschpagan

In [33]:
residuals = re_res.resids
het_test = het_breuschpagan(residuals, exog_het=exog, robust=False)
het_test

(2162.424667795382, 0.0, 117.69773276631277, 5.51077812345784e-93)

In [34]:
residuals = pooled_res.resids
het_test = het_breuschpagan(residuals, exog_het=exog, robust=False)
het_test

(1366.48793528042,
 4.368254638504822e-292,
 73.91881662357707,
 3.3440637677150604e-66)

In [41]:
import numpy as np
import numpy.linalg as la
from scipy import stats

In [42]:
def hausman(fe, re):
    b = fe.params
    B = re.params
    v_b = fe.cov
    v_B = re.cov
    df = b[np.abs(b) < 1e8].size
    chi2 = np.dot((b - B).T, la.inv(v_b - v_B).dot(b - B)) 
    pval = stats.chi2.sf(chi2, df)
    return chi2, df, pval

In [43]:
hausman(be_res, re_res)

(-2731.0448471416003, 7, 1.0)