In [1]:
import pandas as pd
from pathlib import Path

p = Path('')
files = []
for x in p.rglob("*"):
    if str(x).find('.xlsx') != -1:
        files.append(str(x))
files

['emiss_ind.xlsx',
 'emiss_resid.xlsx',
 'emiss_serv.xlsx',
 'emiss_transp.xlsx',
 'nrg_use_ind.xlsx',
 'nrg_use_resid.xlsx',
 'nrg_use_serv.xlsx',
 'nrg_use_transp.xlsx']

In [2]:
output = 0
for i in range(len(files)):
    file = pd.read_excel(files[i])
    file = file.melt(id_vars = 'Country', var_name = 'Year', value_name = files[i].replace('.xlsx', ''))
    file = file.sort_values(['Country', 'Year'], ignore_index=True)
    file.dropna(inplace=True, ignore_index = True)
    file = file.groupby(['Country', 'Year'])[files[i].replace('.xlsx', '')].sum().reset_index()
    if i == 0:
        output = file
    else:
        output = pd.merge_ordered(output, file)
output.dropna(inplace=True, ignore_index = True)
output

,Country,Year,emiss_ind,emiss_resid,emiss_serv,emiss_transp,nrg_use_ind,nrg_use_resid,nrg_use_serv,nrg_use_transp
0,Australia,2000,245.37,54.93,43.84,69.78,2137.72,378.56,212.02,971.87
1,Australia,2005,249.08,62.75,58.95,77.25,2209.92,396.13,260.78,1074.21
2,Australia,2010,262.22,67.73,64.02,81.61,2329.49,427.90,290.19,1129.49
3,Australia,2015,230.79,59.24,65.94,86.79,2230.80,430.40,328.54,1202.70
4,Australia,2016,234.68,60.54,65.19,88.50,2261.80,431.68,322.60,1223.48
...,...,...,...,...,...,...,...,...,...,...
321,Uruguay,2015,2.16,0.66,0.28,3.64,143.40,33.09,12.51,50.72
322,Uruguay,2016,2.09,0.52,0.19,3.73,151.45,34.18,13.07,52.07
323,Uruguay,2017,1.86,0.44,0.13,3.87,154.85,33.39,12.73,54.03
324,Uruguay,2018,2.00,0.49,0.17,3.83,155.97,33.86,13.36,53.43
325,Uruguay,2019,1.86,0.47,0.14,0.04,154.60,35.22,12.85,0.54

In [3]:
#output.to_excel('output1.xlsx')

In [4]:
gdp = pd.read_csv('gdp.csv')

In [5]:
overall = pd.merge_ordered(gdp, output)
overall

,Country,Year,GDP_g,Inflation_g,True Growth,emiss_ind,emiss_resid,emiss_serv,emiss_transp,nrg_use_ind,nrg_use_resid,nrg_use_serv,nrg_use_transp
0,Afghanistan,1961,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1962,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1963,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1964,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1965,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16525,Zimbabwe,2018,5.009867,200.769578,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16526,Zimbabwe,2019,-6.332446,225.394648,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16527,Zimbabwe,2020,-7.816951,604.945864,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16528,Zimbabwe,2021,8.468017,113.294981,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16529,Zimbabwe,2022,3.400000,183.793400,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
overall.dropna(inplace=True, ignore_index = True)
overall

,Country,Year,GDP_g,Inflation_g,True Growth,emiss_ind,emiss_resid,emiss_serv,emiss_transp,nrg_use_ind,nrg_use_resid,nrg_use_serv,nrg_use_transp
0,Australia,2000,3.901171,2.560384,1.0,245.37,54.93,43.84,69.78,2137.72,378.56,212.02,971.87
1,Australia,2005,3.153753,3.824360,0.0,249.08,62.75,58.95,77.25,2209.92,396.13,260.78,1074.21
2,Australia,2010,2.206566,1.157826,1.0,262.22,67.73,64.02,81.61,2329.49,427.90,290.19,1129.49
3,Australia,2015,2.152736,-0.594336,1.0,230.79,59.24,65.94,86.79,2230.80,430.40,328.54,1202.70
4,Australia,2016,2.730548,-0.605177,1.0,234.68,60.54,65.19,88.50,2261.80,431.68,322.60,1223.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,Uruguay,2015,0.370741,9.855420,0.0,2.16,0.66,0.28,3.64,143.40,33.09,12.51,50.72
284,Uruguay,2016,1.689798,8.165458,0.0,2.09,0.52,0.19,3.73,151.45,34.18,13.07,52.07
285,Uruguay,2017,1.740376,5.680184,0.0,1.86,0.44,0.13,3.87,154.85,33.39,12.73,54.03
286,Uruguay,2018,0.156000,7.302102,0.0,2.00,0.49,0.17,3.83,155.97,33.86,13.36,53.43
287,Uruguay,2019,0.744432,8.385848,0.0,1.86,0.47,0.14,0.04,154.60,35.22,12.85,0.54

In [7]:
overall.drop(columns=['True Growth'], inplace = True)

In [8]:
year = pd.Categorical(overall.Year)
overall = overall.set_index(["Country", "Year"])

In [9]:
overall['GDP_lag'] = overall.groupby('Country')['GDP_g'].shift(1)
overall.dropna(inplace=True)
overall

                   GDP_g  Inflation_g  emiss_ind  emiss_resid  emiss_serv  \
Country   Year
Australia 2005  3.153753     3.824360     249.08        62.75       58.95
          2010  2.206566     1.157826     262.22        67.73       64.02
          2015  2.152736    -0.594336     230.79        59.24       65.94
          2016  2.730548    -0.605177     234.68        60.54       65.19
          2017  2.282184     3.743259     229.93        59.44       63.92
...                  ...          ...        ...          ...         ...
Uruguay   2015  0.370741     9.855420       2.16         0.66        0.28
          2016  1.689798     8.165458       2.09         0.52        0.19
          2017  1.740376     5.680184       1.86         0.44        0.13
          2018  0.156000     7.302102       2.00         0.49        0.17
          2019  0.744432     8.385848       1.86         0.47        0.14

                emiss_transp  nrg_use_ind  nrg_use_resid  nrg_use_serv  \
Country   Year
Australia 2005         77.25      2209.92         396.13        260.78
          2010         81.61      2329.49         427.90        290.19
          2015         86.79      2230.80         430.40        328.54
          2016         88.50      2261.80         431.68        322.60
          2017         88.53      2248.77         433.10        321.43
...                      ...          ...            ...           ...
Uruguay   2015          3.64       143.40          33.09         12.51
          2016          3.73       151.45          34.18         13.07
          2017          3.87       154.85          33.39         12.73
          2018          3.83       155.97          33.86         13.36
          2019          0.04       154.60          35.22         12.85

                nrg_use_transp   GDP_lag
Country   Year
Australia 2005         1074.21  3.901171
          2010         1129.49  3.153753
          2015         1202.70  2.206566
          2016         1223.48  2.152736
          2017         1218.46  2.730548
...                        ...       ...
Uruguay   2015           50.72  7.803410
          2016           52.07  0.370741
          2017           54.03  1.689798
          2018           53.43  1.740376
          2019            0.54  0.156000

[255 rows x 11 columns]

In [10]:
exog_vars = overall.columns.tolist()
exog_vars.pop(0)
exog_vars

['Inflation_g',
 'emiss_ind',
 'emiss_resid',
 'emiss_serv',
 'emiss_transp',
 'nrg_use_ind',
 'nrg_use_resid',
 'nrg_use_serv',
 'nrg_use_transp',
 'GDP_lag']

In [11]:
import statsmodels.api as sm
exog = sm.add_constant(overall[exog_vars])

In [12]:
from linearmodels.panel import PooledOLS

In [13]:
mod = PooledOLS(overall.GDP_g, exog)
pooled_res = mod.fit()
pooled_res

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                  GDP_g   R-squared:                        0.0575
Estimator:                  PooledOLS   R-squared (Between):              0.0578
No. Observations:                 255   R-squared (Within):               0.0528
Date:                Wed, Nov 15 2023   R-squared (Overall):              0.0575
Time:                        01:02:28   Log-likelihood                   -664.22
Cov. Estimator:            Unadjusted
                                        F-statistic:                      1.4883
Entities:                          32   P-value                           0.1441
Avg Obs:                       7.9688   Distribution:                  F(10,244)
Min Obs:                       3.0000
Max Obs:                       9.0000   F-statistic (robust):             1.4883
                                        P-value                           0.1441
Time periods:                       9   Distribution:                  F(10,244)
Avg Obs:                       28.333
Min Obs:                       18.000
Max Obs:                       32.000

                               Parameter Estimates
==================================================================================
                Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
----------------------------------------------------------------------------------
const              2.9439     0.4306     6.8373     0.0000      2.0958      3.7920
Inflation_g        0.1085     0.1063     1.0210     0.3083     -0.1008      0.3179
emiss_ind          0.0018     0.0096     0.1847     0.8536     -0.0172      0.0208
emiss_resid        0.0575     0.0421     1.3657     0.1733     -0.0255      0.1405
emiss_serv        -0.0514     0.0503    -1.0229     0.3074     -0.1504      0.0476
emiss_transp       0.0165     0.0655     0.2521     0.8011     -0.1125      0.1455
nrg_use_ind       -0.0005     0.0007    -0.7877     0.4316     -0.0018      0.0008
nrg_use_resid     -0.0040     0.0024    -1.6441     0.1014     -0.0087      0.0008
nrg_use_serv       0.0034     0.0027     1.2667     0.2065     -0.0019      0.0087
nrg_use_transp    -0.0007     0.0047    -0.1600     0.8730     -0.0099      0.0084
GDP_lag           -0.1055     0.0710    -1.4852     0.1388     -0.2454      0.0344
==================================================================================
PanelResults, id: 0x13909e356c0

In [14]:
from linearmodels.panel import RandomEffects

In [15]:
mod = RandomEffects(overall.GDP_g, exog)
re_res = mod.fit()
re_res

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:                  GDP_g   R-squared:                        0.0575
Estimator:              RandomEffects   R-squared (Between):              0.0578
No. Observations:                 255   R-squared (Within):               0.0528
Date:                Wed, Nov 15 2023   R-squared (Overall):              0.0575
Time:                        01:02:28   Log-likelihood                   -664.22
Cov. Estimator:            Unadjusted
                                        F-statistic:                      1.4883
Entities:                          32   P-value                           0.1441
Avg Obs:                       7.9688   Distribution:                  F(10,244)
Min Obs:                       3.0000
Max Obs:                       9.0000   F-statistic (robust):             1.4883
                                        P-value                           0.1441
Time periods:                       9   Distribution:                  F(10,244)
Avg Obs:                       28.333
Min Obs:                       18.000
Max Obs:                       32.000

                               Parameter Estimates
==================================================================================
                Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
----------------------------------------------------------------------------------
const              2.9439     0.4306     6.8373     0.0000      2.0958      3.7920
Inflation_g        0.1085     0.1063     1.0210     0.3083     -0.1008      0.3179
emiss_ind          0.0018     0.0096     0.1847     0.8536     -0.0172      0.0208
emiss_resid        0.0575     0.0421     1.3657     0.1733     -0.0255      0.1405
emiss_serv        -0.0514     0.0503    -1.0229     0.3074     -0.1504      0.0476
emiss_transp       0.0165     0.0655     0.2521     0.8011     -0.1125      0.1455
nrg_use_ind       -0.0005     0.0007    -0.7877     0.4316     -0.0018      0.0008
nrg_use_resid     -0.0040     0.0024    -1.6441     0.1014     -0.0087      0.0008
nrg_use_serv       0.0034     0.0027     1.2667     0.2065     -0.0019      0.0087
nrg_use_transp    -0.0007     0.0047    -0.1600     0.8730     -0.0099      0.0084
GDP_lag           -0.1055     0.0710    -1.4852     0.1388     -0.2454      0.0344
==================================================================================
RandomEffectsResults, id: 0x13909e368f0

In [16]:
from linearmodels.panel import BetweenOLS

In [17]:
exog = sm.add_constant(overall[exog_vars])
mod = BetweenOLS(overall.GDP_g, exog)
be_res = mod.fit(reweight=True) #панели несбалансированы?
be_res

                         BetweenOLS Estimation Summary
================================================================================
Dep. Variable:                  GDP_g   R-squared:                        0.9154
Estimator:                 BetweenOLS   R-squared (Between):              0.9064
No. Observations:                  32   R-squared (Within):              -1.2191
Date:                Wed, Nov 15 2023   R-squared (Overall):             -0.7871
Time:                        01:02:28   Log-likelihood                   -19.227
Cov. Estimator:            Unadjusted
                                        F-statistic:                      23.238
Entities:                          32   P-value                           0.0000
Avg Obs:                       7.9688   Distribution:                   F(10,21)
Min Obs:                       3.0000
Max Obs:                       9.0000   F-statistic (robust):             22.717
                                        P-value                           0.0000
Time periods:                       9   Distribution:                   F(10,21)
Avg Obs:                       28.333
Min Obs:                       18.000
Max Obs:                       32.000

                               Parameter Estimates
==================================================================================
                Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
----------------------------------------------------------------------------------
const             -0.2123     0.3064    -0.6927     0.4961     -0.8496      0.4250
Inflation_g        0.1877     0.0707     2.6542     0.0148      0.0406      0.3348
emiss_ind         -0.0047     0.0069    -0.6710     0.5095     -0.0191      0.0098
emiss_resid       -0.0140     0.0271    -0.5159     0.6113     -0.0704      0.0424
emiss_serv         0.0373     0.0370     1.0076     0.3251     -0.0397      0.1143
emiss_transp       0.0210     0.0317     0.6626     0.5148     -0.0449      0.0869
nrg_use_ind     4.215e-05     0.0005     0.0889     0.9300     -0.0009      0.0010
nrg_use_resid      0.0013     0.0015     0.8595     0.3998     -0.0019      0.0045
nrg_use_serv      -0.0011     0.0022    -0.5127     0.6135     -0.0056      0.0034
nrg_use_transp    -0.0022     0.0023    -0.9922     0.3324     -0.0069      0.0025
GDP_lag            0.9369     0.0742     12.622     0.0000      0.7826      1.0913
==================================================================================
PanelResults, id: 0x13909e9ae90

In [18]:
from linearmodels.panel import compare

In [19]:
print(compare({"BE": be_res, "RE": re_res, "Pooled": pooled_res}, stars=True))

                        Model Comparison
===============================================================
                                BE              RE       Pooled
---------------------------------------------------------------
Dep. Variable                GDP_g           GDP_g        GDP_g
Estimator               BetweenOLS   RandomEffects    PooledOLS
No. Observations                32             255          255
Cov. Est.               Unadjusted      Unadjusted   Unadjusted
R-squared                   0.9154          0.0575       0.0575
R-Squared (Within)         -1.2191          0.0528       0.0528
R-Squared (Between)         0.9064          0.0578       0.0578
R-Squared (Overall)        -0.7871          0.0575       0.0575
F-statistic                 23.238          1.4883       1.4883
P-value (F-stat)            0.0000          0.1441       0.1441
===================== ============ =============== ============
const                      -0.2123       2.9439***    2.9439***
                         (-0.6927)        (6.8373)     (6.8373)
Inflation_g               0.1877**          0.1085       0.1085
                          (2.6542)        (1.0210)     (1.0210)
emiss_ind                  -0.0047          0.0018       0.0018
                         (-0.6710)        (0.1847)     (0.1847)
emiss_resid                -0.0140          0.0575       0.0575
                         (-0.5159)        (1.3657)     (1.3657)
emiss_serv                  0.0373         -0.0514      -0.0514
                          (1.0076)       (-1.0229)    (-1.0229)
emiss_transp                0.0210          0.0165       0.0165
                          (0.6626)        (0.2521)     (0.2521)
nrg_use_ind              4.215e-05         -0.0005      -0.0005
                          (0.0889)       (-0.7877)    (-0.7877)
nrg_use_resid               0.0013         -0.0040      -0.0040
                          (0.8595)       (-1.6441)    (-1.6441)
nrg_use_serv               -0.0011          0.0034       0.0034
                         (-0.5127)        (1.2667)     (1.2667)
nrg_use_transp             -0.0022         -0.0007      -0.0007
                         (-0.9922)       (-0.1600)    (-0.1600)
GDP_lag                  0.9369***         -0.1055      -0.1055
                          (12.622)       (-1.4852)    (-1.4852)
---------------------------------------------------------------

T-stats reported in parentheses

In [20]:
from statsmodels.stats.diagnostic import het_breuschpagan

In [21]:
residuals = re_res.resids

In [22]:
het_test = het_breuschpagan(residuals, exog_het=exog, robust=False)

In [23]:
het_test

(102.90124774561491,
 1.429025720688266e-17,
 1.9358770261592837,
 0.04114292521093419)

In [24]:
residuals = pooled_res.resids
het_test = het_breuschpagan(residuals, exog_het=exog, robust=False)

In [25]:
het_test

(102.90124774561491,
 1.429025720688266e-17,
 1.9358770261592837,
 0.04114292521093419)

In [32]:
import numpy.linalg as la
import numpy as np
from scipy import stats

In [33]:
def hausman(fe, re):
    b = fe.params
    B = re.params
    v_b = fe.cov
    v_B = re.cov
    df = b[np.abs(b) < 1e8].size
    chi2 = np.dot((b - B).T, la.inv(v_b - v_B).dot(b - B)) 
    pval = stats.chi2.sf(chi2, df)
    return chi2, df, pval

In [34]:
hausman(be_res, re_res)

(2723.5553336355106, 11, 0.0)